Update time dependency to 0.3.36 so that it compiles with newest Rust
This addresses the following build failure with Rust 1.80:

    error[E0282]: type annotations needed for `Box<_>`
      --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.30/src/format_description/parse/mod.rs:83:9
       |
    83 |     let items = format_items
       |         ^^^^^
    ...
    86 |     Ok(items.into())
       |              ---- type must be known at this point