solana-ibc: define missing custom_panic handler
With the switch to custom entrypoint we also need to provide custom
panic handler.  Without it deploying the contract fails with the
following:

> Error: ELF error: ELF error: Unresolved symbol (custom_panic) at
> instruction #265306 (ELF file offset 0x2061e8)
>
> There was a problem deploying: Output { status:
> ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }.